<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PublicMarketingContentSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedAchievements();
        $this->seedStories();
        $this->seedOfflineCourses();
        $this->seedWorkshops();
    }

    private function seedAchievements(): void
    {
        if (! Schema::hasTable('home_achievements')) {
            return;
        }

        $rows = array (
  0 => 
  array (
    'id' => 1,
    'kind' => 'gallery',
    'gallery_category' => 'Seminar',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941045/lms/course-thumbnails/home/achievements/gallery-ywqg9oab.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:09:02',
    'updated_at' => '2026-04-23 10:43:58',
  ),
  1 => 
  array (
    'id' => 2,
    'kind' => 'gallery',
    'gallery_category' => 'Seminar',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941123/lms/course-thumbnails/home/achievements/gallery-nipvgpp3.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:10:07',
    'updated_at' => '2026-04-23 10:45:16',
  ),
  2 => 
  array (
    'id' => 3,
    'kind' => 'gallery',
    'gallery_category' => 'Seminar',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941168/lms/course-thumbnails/home/achievements/gallery-7o4g6fp8.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:10:58',
    'updated_at' => '2026-04-23 10:46:01',
  ),
  3 => 
  array (
    'id' => 4,
    'kind' => 'gallery',
    'gallery_category' => 'Seminar',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941240/lms/course-thumbnails/home/achievements/gallery-puzpraxc.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:12:07',
    'updated_at' => '2026-04-23 10:47:13',
  ),
  4 => 
  array (
    'id' => 5,
    'kind' => 'gallery',
    'gallery_category' => 'Seminar',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941275/lms/course-thumbnails/home/achievements/gallery-ll0nlmi5.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:12:31',
    'updated_at' => '2026-04-23 10:47:47',
  ),
  5 => 
  array (
    'id' => 6,
    'kind' => 'gallery',
    'gallery_category' => 'Seminar',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941335/lms/course-thumbnails/home/achievements/gallery-dp3bzspj.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:12:58',
    'updated_at' => '2026-04-23 10:48:48',
  ),
  6 => 
  array (
    'id' => 7,
    'kind' => 'gallery',
    'gallery_category' => 'Seminar',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941443/lms/course-thumbnails/home/achievements/gallery-forjgbr3.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:13:52',
    'updated_at' => '2026-04-23 10:50:36',
  ),
  7 => 
  array (
    'id' => 8,
    'kind' => 'gallery',
    'gallery_category' => 'Students Achivements',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941512/lms/course-thumbnails/home/achievements/gallery-0o9kf0d3.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:18:24',
    'updated_at' => '2026-04-23 10:51:44',
  ),
  8 => 
  array (
    'id' => 9,
    'kind' => 'gallery',
    'gallery_category' => 'Students Achivements',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941566/lms/course-thumbnails/home/achievements/gallery-ktsqnawq.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:18:50',
    'updated_at' => '2026-04-23 10:52:39',
  ),
  9 => 
  array (
    'id' => 10,
    'kind' => 'gallery',
    'gallery_category' => 'Students Achivements',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941631/lms/course-thumbnails/home/achievements/gallery-1mwhmitb.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:19:09',
    'updated_at' => '2026-04-23 10:53:43',
  ),
  10 => 
  array (
    'id' => 11,
    'kind' => 'gallery',
    'gallery_category' => 'Students Achivements',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941729/lms/course-thumbnails/home/achievements/gallery-akoknhpz.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:19:31',
    'updated_at' => '2026-04-23 10:55:21',
  ),
  11 => 
  array (
    'id' => 12,
    'kind' => 'gallery',
    'gallery_category' => 'Founder Achievements & Awards',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941884/lms/course-thumbnails/home/achievements/gallery-rerytmlb.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:28:30',
    'updated_at' => '2026-04-23 10:57:56',
  ),
  12 => 
  array (
    'id' => 13,
    'kind' => 'gallery',
    'gallery_category' => 'Founder Achievements & Awards',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941929/lms/course-thumbnails/home/achievements/gallery-vrsf7pq9.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:28:59',
    'updated_at' => '2026-04-23 10:58:42',
  ),
  13 => 
  array (
    'id' => 14,
    'kind' => 'gallery',
    'gallery_category' => 'Founder Achievements & Awards',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776940664/lms/course-thumbnails/home/achievements/gallery-phnaetdw.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2026-04-16 08:29:22',
    'updated_at' => '2026-04-23 10:37:36',
  ),
  14 => 
  array (
    'id' => 15,
    'kind' => 'gallery',
    'gallery_category' => 'Founder Achievements & Awards',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776940759/lms/course-thumbnails/home/achievements/gallery-ucmlgibm.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2026-04-16 08:30:12',
    'updated_at' => '2026-04-23 10:39:11',
  ),
  15 => 
  array (
    'id' => 16,
    'kind' => 'gallery',
    'gallery_category' => 'Founder Achievements & Awards',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776940860/lms/course-thumbnails/home/achievements/gallery-48npiwp4.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2026-04-16 08:31:09',
    'updated_at' => '2026-04-23 10:40:53',
  ),
  16 => 
  array (
    'id' => 17,
    'kind' => 'gallery',
    'gallery_category' => 'Founder Achievements & Awards',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776940943/lms/course-thumbnails/home/achievements/gallery-2ld3b0vd.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2026-04-16 08:31:41',
    'updated_at' => '2026-04-23 10:42:16',
  ),
  17 => 
  array (
    'id' => 18,
    'kind' => 'gallery',
    'gallery_category' => 'Founder Achievements & Awards',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776940808/lms/course-thumbnails/home/achievements/gallery-fehvdnqy.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 2,
    'created_at' => '2026-04-16 08:32:05',
    'updated_at' => '2026-04-23 10:40:02',
  ),
  18 => 
  array (
    'id' => 19,
    'kind' => 'gallery',
    'gallery_category' => 'Founder Achievements & Awards',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776941998/lms/course-thumbnails/home/achievements/gallery-n9ydafie.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:32:30',
    'updated_at' => '2026-04-23 10:59:50',
  ),
  19 => 
  array (
    'id' => 20,
    'kind' => 'gallery',
    'gallery_category' => 'Seminar',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776942056/lms/course-thumbnails/home/achievements/gallery-6ziwyswr.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:37:31',
    'updated_at' => '2026-04-23 11:00:48',
  ),
  20 => 
  array (
    'id' => 21,
    'kind' => 'gallery',
    'gallery_category' => 'Students Reviews',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776942114/lms/course-thumbnails/home/achievements/gallery-zgccnixc.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:56:04',
    'updated_at' => '2026-04-23 11:01:47',
  ),
  21 => 
  array (
    'id' => 22,
    'kind' => 'gallery',
    'gallery_category' => 'Students Reviews',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776942185/lms/course-thumbnails/home/achievements/gallery-exhbqwg4.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 08:56:30',
    'updated_at' => '2026-04-23 11:02:58',
  ),
  22 => 
  array (
    'id' => 23,
    'kind' => 'gallery',
    'gallery_category' => 'Students Reviews',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776942281/lms/course-thumbnails/home/achievements/gallery-tfd8fj8z.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:10:35',
    'updated_at' => '2026-04-23 11:04:34',
  ),
  23 => 
  array (
    'id' => 24,
    'kind' => 'gallery',
    'gallery_category' => 'Students Reviews',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776942396/lms/course-thumbnails/home/achievements/gallery-opncnzjp.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:10:59',
    'updated_at' => '2026-04-23 11:06:29',
  ),
  24 => 
  array (
    'id' => 25,
    'kind' => 'gallery',
    'gallery_category' => 'Students Reviews',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776942461/lms/course-thumbnails/home/achievements/gallery-9hv0tpsa.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:11:52',
    'updated_at' => '2026-04-23 11:07:34',
  ),
  25 => 
  array (
    'id' => 26,
    'kind' => 'gallery',
    'gallery_category' => 'Students Reviews',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776942520/lms/course-thumbnails/home/achievements/gallery-9hwpenzl.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:12:22',
    'updated_at' => '2026-04-23 11:08:33',
  ),
  26 => 
  array (
    'id' => 27,
    'kind' => 'gallery',
    'gallery_category' => 'Students Reviews',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776942584/lms/course-thumbnails/home/achievements/gallery-fghlshg1.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:12:59',
    'updated_at' => '2026-04-23 11:09:37',
  ),
  27 => 
  array (
    'id' => 28,
    'kind' => 'gallery',
    'gallery_category' => 'Students Reviews',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776942637/lms/course-thumbnails/home/achievements/gallery-v9hwsp1b.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:13:29',
    'updated_at' => '2026-04-23 11:10:30',
  ),
  28 => 
  array (
    'id' => 29,
    'kind' => 'gallery',
    'gallery_category' => 'Students Reviews',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776942744/lms/course-thumbnails/home/achievements/gallery-ytr7j2cg.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:21:11',
    'updated_at' => '2026-04-23 11:12:17',
  ),
  29 => 
  array (
    'id' => 30,
    'kind' => 'gallery',
    'gallery_category' => 'Students Reviews',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776940996/lms/course-thumbnails/home/achievements/gallery-xphssrcb.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 1,
    'created_at' => '2026-04-16 09:21:41',
    'updated_at' => '2026-04-23 10:43:10',
  ),
  30 => 
  array (
    'id' => 31,
    'kind' => 'gallery',
    'gallery_category' => 'Seminar',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776942831/lms/course-thumbnails/home/achievements/gallery-gnsw6kvk.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:22:11',
    'updated_at' => '2026-04-23 11:13:45',
  ),
  31 => 
  array (
    'id' => 32,
    'kind' => 'gallery',
    'gallery_category' => 'Seminar',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776942919/lms/course-thumbnails/home/achievements/gallery-beua5cpn.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:22:33',
    'updated_at' => '2026-04-23 11:15:13',
  ),
  32 => 
  array (
    'id' => 33,
    'kind' => 'gallery',
    'gallery_category' => 'Seminar',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776942996/lms/course-thumbnails/home/achievements/gallery-pomr5i4w.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:23:00',
    'updated_at' => '2026-04-23 11:16:29',
  ),
  33 => 
  array (
    'id' => 34,
    'kind' => 'gallery',
    'gallery_category' => 'Seminar',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776943052/lms/course-thumbnails/home/achievements/gallery-qleqzmlo.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:23:38',
    'updated_at' => '2026-04-23 11:17:25',
  ),
  34 => 
  array (
    'id' => 35,
    'kind' => 'gallery',
    'gallery_category' => 'Festival & Events Celebration',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943135/lms/course-thumbnails/home/achievements/gallery-1tz150pi.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:31:48',
    'updated_at' => '2026-04-23 11:18:48',
  ),
  35 => 
  array (
    'id' => 36,
    'kind' => 'gallery',
    'gallery_category' => 'Festival & Events Celebration',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943185/lms/course-thumbnails/home/achievements/gallery-a93svnxq.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:32:21',
    'updated_at' => '2026-04-23 11:19:37',
  ),
  36 => 
  array (
    'id' => 37,
    'kind' => 'gallery',
    'gallery_category' => 'Festival & Events Celebration',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943233/lms/course-thumbnails/home/achievements/gallery-rd9olegt.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:32:50',
    'updated_at' => '2026-04-23 11:20:26',
  ),
  37 => 
  array (
    'id' => 38,
    'kind' => 'gallery',
    'gallery_category' => 'Festival & Events Celebration',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943267/lms/course-thumbnails/home/achievements/gallery-wn4vhqmy.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:33:09',
    'updated_at' => '2026-04-23 11:21:00',
  ),
  38 => 
  array (
    'id' => 39,
    'kind' => 'gallery',
    'gallery_category' => 'Festival & Events Celebration',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943341/lms/course-thumbnails/home/achievements/gallery-apwocczj.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:33:34',
    'updated_at' => '2026-04-23 11:22:13',
  ),
  39 => 
  array (
    'id' => 40,
    'kind' => 'gallery',
    'gallery_category' => 'Festival & Events Celebration',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943388/lms/course-thumbnails/home/achievements/gallery-igvdi4pa.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:33:53',
    'updated_at' => '2026-04-23 11:23:01',
  ),
  40 => 
  array (
    'id' => 41,
    'kind' => 'gallery',
    'gallery_category' => 'Festival & Events Celebration',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943431/lms/course-thumbnails/home/achievements/gallery-5fqyfqah.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:34:10',
    'updated_at' => '2026-04-23 11:23:43',
  ),
  41 => 
  array (
    'id' => 42,
    'kind' => 'gallery',
    'gallery_category' => 'Festival & Events Celebration',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776943523/lms/course-thumbnails/home/achievements/gallery-coqia5jh.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:38:15',
    'updated_at' => '2026-04-23 11:25:16',
  ),
  42 => 
  array (
    'id' => 43,
    'kind' => 'gallery',
    'gallery_category' => 'Festival & Events Celebration',
    'gallery_category_order' => 0,
    'eyebrow' => NULL,
    'title' => NULL,
    'copy' => NULL,
    'stat' => NULL,
    'icon' => NULL,
    'points' => '[]',
    'media_url' => 'https://res.cloudinary.com/dqxg5hhfi/video/upload/v1776943656/lms/course-thumbnails/home/achievements/gallery-w49cvcxk.mp4',
    'media_type' => 'video',
    'media_provider' => 'cloudinary',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-16 09:38:38',
    'updated_at' => '2026-04-23 11:27:29',
  ),
);

        foreach ($rows as $row) {
            DB::table('home_achievements')->updateOrInsert(
                ['id' => $row['id']],
                $row
            );
        }
    }

    private function seedStories(): void
    {
        if (! Schema::hasTable('home_stories')) {
            return;
        }

        $rows = array (
  0 => 
  array (
    'id' => 1,
    'type' => 'placement',
    'name' => 'Vivek Mali',
    'course' => 'Data Analytics',
    'comment' => 'The classes felt personal and practical. I always knew what to work on next, and the mentor feedback kept me consistent.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776944125/lms/course-thumbnails/home/stories/vivek-mali-mu9mlvhg.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => 'Luthar Group',
    'role' => 'PERN Analyst',
    'package' => '3.5 LPA',
    'shared_at' => '2026-03-20',
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 5,
    'created_at' => '2026-04-14 10:03:08',
    'updated_at' => '2026-04-23 11:35:17',
  ),
  1 => 
  array (
    'id' => 2,
    'type' => 'placement',
    'name' => 'Chandramukhi',
    'course' => 'Data Analytics',
    'comment' => 'The classes felt personal and practical. I always knew what to work on next, and the mentor feedback kept me consistent.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776944150/lms/course-thumbnails/home/stories/chandramukhi-pxfh9nge.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => 'Luthar Group',
    'role' => 'FICO Analyst',
    'package' => '3.5 LPA',
    'shared_at' => '2006-03-20',
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 6,
    'created_at' => '2026-04-14 10:44:22',
    'updated_at' => '2026-04-23 11:35:42',
  ),
  2 => 
  array (
    'id' => 3,
    'type' => 'placement',
    'name' => 'Amaan Tarekh',
    'course' => 'Data Analytics',
    'comment' => 'The classes felt personal and practical. I always knew what to work on next, and the mentor feedback kept me consistent.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943983/lms/course-thumbnails/home/stories/amaan-tarekh-hf35luvm.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => 'Luthar Group',
    'role' => 'PERN Analyst',
    'package' => '3.5 LPA',
    'shared_at' => '2006-03-20',
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 1,
    'created_at' => '2026-04-14 10:45:38',
    'updated_at' => '2026-04-23 11:32:55',
  ),
  3 => 
  array (
    'id' => 4,
    'type' => 'placement',
    'name' => 'Foram Parekh',
    'course' => 'Data Analytics',
    'comment' => 'The classes felt personal and practical. I always knew what to work on next, and the mentor feedback kept me consistent.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943861/lms/course-thumbnails/home/stories/foram-parekh-kww4hlqr.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => 'Luthar Group',
    'role' => 'FICO Analyst',
    'package' => '3.5 LPA',
    'shared_at' => '2006-03-20',
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 0,
    'created_at' => '2026-04-14 10:47:05',
    'updated_at' => '2026-04-23 11:30:53',
  ),
  4 => 
  array (
    'id' => 6,
    'type' => 'placement',
    'name' => 'Darshit Patel',
    'course' => 'Data Analytics',
    'comment' => 'The classes felt personal and practical. I always knew what to work on next, and the mentor feedback kept me consistent.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943749/lms/course-thumbnails/home/stories/darshit-patel-lxbfbb4z.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => 'Luthar Group',
    'role' => 'Data Analyst',
    'package' => '3.5 LPA',
    'shared_at' => '2006-03-20',
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 9,
    'created_at' => '2026-04-14 10:48:12',
    'updated_at' => '2026-04-23 11:29:02',
  ),
  5 => 
  array (
    'id' => 7,
    'type' => 'placement',
    'name' => 'Vishwa Jadav',
    'course' => 'Data Analytics',
    'comment' => 'The classes felt personal and practical. I always knew what to work on next, and the mentor feedback kept me consistent.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943830/lms/course-thumbnails/home/stories/vishwa-jadav-hlwzfm1r.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => 'Porce technocret pvt.Ltd',
    'role' => 'Data Analyst',
    'package' => '4 LPA',
    'shared_at' => NULL,
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 0,
    'created_at' => '2026-04-14 11:49:32',
    'updated_at' => '2026-04-23 11:30:23',
  ),
  6 => 
  array (
    'id' => 8,
    'type' => 'placement',
    'name' => 'Diya Patel',
    'course' => NULL,
    'comment' => 'The classes felt personal and practical. I always knew what to work on next, and the mentor feedback kept me consistent.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943942/lms/course-thumbnails/home/stories/diya-patel-labxjfai.png',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => 'Inkly Solution',
    'role' => NULL,
    'package' => NULL,
    'shared_at' => NULL,
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 1,
    'created_at' => '2026-04-14 11:50:59',
    'updated_at' => '2026-04-23 11:32:14',
  ),
  7 => 
  array (
    'id' => 9,
    'type' => 'placement',
    'name' => 'Janvi Pawar',
    'course' => NULL,
    'comment' => 'The classes felt personal and practical. I always knew what to work on next, and the mentor feedback kept me consistent.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776944051/lms/course-thumbnails/home/stories/janvi-pawar-gn4q8dmc.png',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => 'Phoenix Assurance Pvt Ltd.',
    'role' => NULL,
    'package' => NULL,
    'shared_at' => NULL,
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 3,
    'created_at' => '2026-04-14 11:51:50',
    'updated_at' => '2026-04-23 11:34:04',
  ),
  8 => 
  array (
    'id' => 10,
    'type' => 'placement',
    'name' => 'Sai Kumar',
    'course' => 'Data Science',
    'comment' => 'The classes felt personal and practical. I always knew what to work on next, and the mentor feedback kept me consistent.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776944018/lms/course-thumbnails/home/stories/sai-kumar-yytjpso1.png',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => 'IDFC Bank',
    'role' => 'Data Science',
    'package' => '5 LPA',
    'shared_at' => NULL,
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 2,
    'created_at' => '2026-04-14 11:52:54',
    'updated_at' => '2026-04-23 11:33:30',
  ),
  9 => 
  array (
    'id' => 13,
    'type' => 'success_story',
    'name' => 'Sai Kumar',
    'course' => 'Data Science',
    'comment' => 'One of the best academy where we can learn data science, data analyst by expert No.1 Classes for it course.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776944186/lms/course-thumbnails/home/stories/sai-kumar-mfdg1trb.png',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => NULL,
    'role' => NULL,
    'package' => NULL,
    'shared_at' => NULL,
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 0,
    'created_at' => '2026-04-14 12:04:33',
    'updated_at' => '2026-04-23 11:36:18',
  ),
  10 => 
  array (
    'id' => 14,
    'type' => 'success_story',
    'name' => 'Foram savani',
    'course' => 'Data Analyst',
    'comment' => 'If you want to learn data science, data analytics, and  digital marketing, i highly recommend this organization\'s best training and best service by Kajal mam.',
    'avatar' => NULL,
    'media_type' => 'image',
    'media_provider' => 'url',
    'rating' => 5,
    'company' => NULL,
    'role' => NULL,
    'package' => NULL,
    'shared_at' => NULL,
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 1,
    'created_at' => '2026-04-14 12:07:46',
    'updated_at' => '2026-04-14 12:07:46',
  ),
  11 => 
  array (
    'id' => 15,
    'type' => 'placement',
    'name' => 'Suraj Sen',
    'course' => 'Data Analytics',
    'comment' => 'The classes felt personal and practical. I always knew what to work on next, and the mentor feedback kept me consistent.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943801/lms/course-thumbnails/home/stories/suraj-sen-lzcfsxpn.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => 'Accenture',
    'role' => 'Data Analyst',
    'package' => '12 LPA',
    'shared_at' => NULL,
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 0,
    'created_at' => '2026-04-16 05:27:37',
    'updated_at' => '2026-04-23 11:29:53',
  ),
  12 => 
  array (
    'id' => 16,
    'type' => 'placement',
    'name' => 'Asad Ali',
    'course' => 'Data Science',
    'comment' => 'The classes felt personal and practical. I always knew what to work on next, and the mentor feedback kept me consistent.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943913/lms/course-thumbnails/home/stories/asad-ali-jyd8o1s1.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => 'Rimbuss',
    'role' => 'Data Science',
    'package' => '4 LPA',
    'shared_at' => NULL,
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 1,
    'created_at' => '2026-04-16 05:28:58',
    'updated_at' => '2026-04-23 11:31:45',
  ),
  13 => 
  array (
    'id' => 17,
    'type' => 'placement',
    'name' => 'Anjali Tiwari',
    'course' => 'Data Engineer',
    'comment' => 'The classes felt personal and practical. I always knew what to work on next, and the mentor feedback kept me consistent.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776943887/lms/course-thumbnails/home/stories/anjali-tiwari-b6b28lng.jpg',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => 'Wipro',
    'role' => 'Data Engineer',
    'package' => '5 LPA',
    'shared_at' => NULL,
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 1,
    'created_at' => '2026-04-16 05:47:11',
    'updated_at' => '2026-04-23 11:31:20',
  ),
  14 => 
  array (
    'id' => 18,
    'type' => 'placement',
    'name' => 'Guun Mahendra Hiran',
    'course' => NULL,
    'comment' => 'The classes felt personal and practical. I always knew what to work on next, and the mentor feedback kept me consistent.',
    'avatar' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776944087/lms/course-thumbnails/home/stories/guun-mahendra-hiran-tsobyprk.png',
    'media_type' => 'image',
    'media_provider' => 'cloudinary',
    'rating' => 5,
    'company' => 'Luthar Group',
    'role' => 'Data Analyst',
    'package' => '3.5 LPA',
    'shared_at' => NULL,
    'is_active' => 1,
    'show_in_placement_hero' => 0,
    'sort_order' => 4,
    'created_at' => '2026-04-16 06:00:43',
    'updated_at' => '2026-04-23 11:34:40',
  ),
);

        foreach ($rows as $row) {
            DB::table('home_stories')->updateOrInsert(
                ['id' => $row['id']],
                $row
            );
        }
    }

    private function seedOfflineCourses(): void
    {
        if (! Schema::hasTable('offline_courses')) {
            return;
        }

        $rows = array (
  0 => 
  array (
    'id' => 2,
    'title' => 'Data Science',
    'slug' => 'data-science',
    'summary' => 'The Data Science Certification Program is designed for freshers, working professionals, and
freelancers who want to become industry-ready Data Scientists. This program covers everything
from Python, SQL, Machine Learning, and Deep Learning to Big Data, NLP, and Cloud
Deployment.


With real-world projects, case studies, and hands-on training, you’ll gain the skills companies
demand in AI, Machine Learning, and Data-Driven Decision Making.',
    'details' => NULL,
    'thumbnail' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776944422/lms/course-thumbnails/courses/offline/data-science-thumbnail-lcsi1crv.jpg',
    'campus' => NULL,
    'schedule_label' => NULL,
    'duration_label' => '8-10 Months',
    'validity_label' => '1.5 Years',
    'delivery_mode' => 'Online & Offline',
    'placement_label' => '100% Job Placement Guarantee Assurance',
    'audience' => 'Working Professional',
    'batch_size' => NULL,
    'language' => 'Python, SQL, Machine Learning.',
    'level' => 'Beginner To Advanced',
    'highlights' => '["Automated Railway Ticket Verification System","QR\\/barcode scan (pyzbar\\/Zxing)","Face verification (OpenCV + TensorFlow\\/PyTorch\\/DeepFace)","occupancy detection (YOLO\\/Detectron2)","real-time events (Kafka\\/RabbitMQ)","API layer (FastAPI)","storage (MongoDB\\/PostgreSQL)","Power BI command center.","Alerts & notifications (Twilio\\/SendGrid)"]',
    'curriculum_modules' => '[{"title":"Data Analysis Foundation","duration":"4-5 Months","topics":[{"title":"Excel & Google Sheets (1 Month)","details":"\\u25cf Formulas & Functions \\u2192 VLOOKUP, HLOOKUP, INDEX, MATCH, IF, nested\\r\\nformulas.\\r\\n\\r\\n\\u25cf Data Cleaning \\u2192 Handling duplicates, missing values, formatting.\\r\\n\\r\\n\\u25cf Pivot Tables & Charts \\u2192 Summarising datasets, visual reporting.\\r\\n\\r\\n\\u25cf Automation with VBA \\u2192 Macros for repetitive tasks.\\r\\n\\r\\n\\u25cf Google Sheets \\u2192 Collaboration, add-ons, automation scripts"},{"title":"SQL(MySQL) & MongoDB (1.5 Months)","details":"\\u25cf SQL Basics: SELECT, WHERE, ORDER BY, GROUP BY.\\r\\n\\u25cf Intermediate: Joins (INNER, LEFT, RIGHT, FULL), Subqueries, CASE statements.\\r\\n\\u25cf Advanced: CTEs, Window Functions (ROW_NUMBER, RANK, LAG, LEAD), Stored\\r\\nProcedures, Indexes.\\r\\n\\u25cf MongoDB (NoSQL): CRUD, Aggregation Pipeline, Indexing.\\r\\nSQL manages structured data (banking, ERP, CRM), MongoDB powers e-commerce,\\r\\nIoT, and user behaviour apps."},{"title":"Python for Data Analysis (2 Months)","details":"\\u25cf Fundamentals: Data types, loops, OOP, error handling.\\r\\n\\u25cf Libraries: NumPy (arrays), Pandas (wrangling), Matplotlib\\/Seaborn\\/Plotly (visuals).\\r\\n\\u25cf EDA: Cleaning, profiling, missing values, trend detection."},{"title":"Business Intelligence & Visualisation (1 Month)","details":"\\u25cf Power BI: DAX, dashboards, publishing, mobile reports.\\r\\n\\u25cf Looker Studio: Real-time dashboards from SQL\\/Sheets.\\r\\nTransforms raw data into insights for decision-making"},{"title":"Project Management Tools (2 Weeks)","details":"Jira, Trello, Asana, Agile, Scrum basics.\\r\\nPrepares you for corporate collaboration"}],"project":"Automated reporting in Excel (VBA), E-commerce dashboard in Power BI."},{"title":"Python for Data Science","duration":"2.5 Months","topics":[{"title":"","details":"\\u25cf Fundamentals \\u2192 OOP: Data types, control flow, functions, error handling, OOP for\\r\\nreusable DS utilities; file I\\/O (CSV\\/JSON).\\r\\n\\u25cf Core Libraries: NumPy (arrays, vectorisation), Pandas (joins, groupby, missing data,\\r\\ntime-series), Matplotlib\\/Seaborn\\/Plotly (static + interactive visuals).\\r\\n\\u25cf Stats Basics for DS: Mean\\/median\\/variance\\/std, distributions; quick inference to guide\\r\\nEDA."}],"project":"Multi-source EDA + insight report (notebook + HTML export + slide deck)."},{"title":"Core Data Science Topics","duration":"2.5 Months","topics":[{"title":"Data Collection & Cleaning (1 Month)","details":"Pandas\\/NumPy for wrangling; BeautifulSoup\\/Scrapy for web data; outlier\\/missing-value\\r\\ntreatment; scaling\\/encoding."},{"title":"Data Visualisation (3 Weeks)","details":"Matplotlib\\/Seaborn\\/Plotly, trend, correlation, distribution, heatmaps; interactive\\r\\ndrilldowns for product teams"},{"title":"Statistics & Hypothesis Testing (3 Weeks)","details":"SciPy\\/Statsmodels: t\\/chi-square\\/ANOVA, regression diagnostics, A\\/B test readouts;\\r\\nconfidence intervals & effect sizes."}],"project":"Customer 360 cleaning pipeline + profiling report,  Interactive product performance explorer (Plotly),   Marketing lift study with executive summary."},{"title":"Machine Learning","duration":"2 Months","topics":[{"title":"","details":"\\u25cf Supervised: Linear\\/Logistic, Trees\\/Random Forests, Gradient Boosting\\r\\n(XGBoost\\/LightGBM\\/CatBoost).\\r\\n\\u25cf Unsupervised: K-means\\/hierarchical, PCA\\/t-SNE\\/UMAP for dimensionality reduction.\\r\\n\\u25cf Evaluation: Train\\/validate\\/test splits; cross-validation; metrics (Accuracy,\\r\\nPrecision\\/Recall\\/F1, ROC-AUC, MAE\\/MSE\\/R\\u00b2).\\r\\n\\u25cf Model Tuning: Optuna\\/Hyperopt\\/RandomizedSearch; pipelines for production-ready\\r\\ntraining."}],"project":"Churn\\/Fraud\\/Credit-risk prediction with hyperparameter-tuned models & SHAP insights"},{"title":"Deep Learning","duration":"2 Months","topics":[{"title":"","details":"\\u25cf Foundations: Perceptron, activations (ReLU\\/sigmoid), forward\\/backprop, losses;\\r\\noptimisers (SGD\\/Adam\\/RMSprop); regularisation (dropout, L1\\/L2, batch norm).\\r\\n\\u25cf CNNs: Image classification\\/defect detection.\\r\\n\\u25cf RNNs\\/LSTM\\/GRU: Sequences & time-series forecasting.\\r\\n\\u25cf Transformers & LLMs: Attention, BERT, GPT; embeddings, fine-tuning & RAG basics\\r\\nfor domain Q&A.\\r\\n\\u25cf GANs\\/Autoencoders: Synthesis, anomaly detection, compression.\\r\\n\\u25cf Explainability: LIME\\/SHAP, gradient-based saliency for trust in models."}],"project":"End-to-end DL use case (e.g., image classifier with API deployment)."},{"title":"Big Data & Distributed ComputingBig Data & Distributed Computing","duration":"1 Month","topics":[{"title":"","details":"\\u25cf Dask for out-of-memory Pandas; PySpark for distributed ETL\\/ML; partitioning &\\r\\ncaching strategies."}],"project":"Millions-row analytics in Spark + BI connector"},{"title":"NLP & Applied","duration":"1 Month","topics":[{"title":"","details":"NLTK\\/SpaCy for tokenisation\\/NER; Hugging Face for transformers; prompt engineering for LLM tasks."}],"project":"Sentiment & topic insights dashboard + chatbot prototype."},{"title":"Deployment & MLOps","duration":"1 Month","topics":[{"title":"","details":"\\u25cf APIs: Flask\\/FastAPI to serve models; input validation; logging.\\r\\n\\u25cf Ops: Docker\\/Kubernetes for portable\\/scalable serving; MLflow for experiment tracking;\\r\\nAirflow for training pipelines; DVC for data\\/versioning.\\r\\n\\u25cf Cloud (Included): Basics on AWS\\/Azure\\/GCP, compute, storage, scheduled jobs,\\r\\nmonitoring."}],"project":"Model-in-production with CI\\/CD, monitoring & rollback plan."},{"title":"Databases: SQL & MongoDB","duration":"2 Months","topics":[{"title":"SQL (Basic \\u2192 Advanced)","details":"\\u25cb Data types\\/operators; SELECT\\/FROM\\/WHERE; GROUP BY; ORDER\\r\\nBY\\/LIMIT.\\r\\n\\u25cb Joins (INNER\\/LEFT\\/RIGHT\\/FULL), subqueries, CTE,CASE; window functions\\r\\n(ROW_NUMBER\\/RANK\\/DENSE_RANK\\/LAG\\/LEAD).\\r\\n\\u25cb CTEs; HAVING; string\\/date functions; DML\\r\\n(INSERT\\/UPDATE\\/DELETE\\/MERGE).\\r\\n\\u25cb Performance: Indexes, query plans, partitioning; views; transactions for integrity."},{"title":"","details":"\\u25cf MongoDB: CRUD, aggregation pipeline, indexes for semi-structured data.\\r\\n\\u25cf Tools (with purpose): SQL Workbench\\/SSMS for IDE workflows; SQLAlchemy+pandas\\r\\nfor\\r\\nPython-DB pipelines; cloud warehouses (BigQuery\\/Redshift\\/Snowflake) for large-scale\\r\\nanalytics;\\r\\n\\u25cf Power BI\\/Tableau to visualise SQL outputs; Airflow to schedule SQL\\/ETL."}],"project":"SQL feature-store + automated daily refresh feeding a production model."},{"title":"Automation in Data Science","duration":"","topics":[{"title":"","details":"\\u25cf Pipelines: Airflow\\/Luigi for ETL; cron jobs for retraining\\/refresh.\\r\\n\\u25cf AutoML: TPOT\\/Auto-sklearn to try many models\\/features automatically.\\r\\n\\u25cf Tracking & Reporting: MLflow\\/DVC for runs\\/data; Papermill for parameterised\\r\\nreporting notebooks; scheduled email\\/HTML reports."}],"project":""}]',
    'additional_benefits' => '["\\u2714 100% Job Placement Guarantee","\\u2714 ATS-Friendly Resume Building & LinkedIn Optimisation","\\u2714 Mock Interviews & Capstone Projects","\\u2714 GitHub Portfolio Building","\\u2714 Freelancing Guidance (Upwork Fiverr Freelancer)","\\u2714 Alternate Saturday: Personality Development Sessions"]',
    'learner_note' => 'After completing this program, a fresher will have the knowledge of a 1+ year experienced Data
Scientist, and working professionals will be ready to switch or upskill into high-paying AI
& ML roles.',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-21 07:17:09',
    'updated_at' => '2026-04-23 11:40:15',
    'category_name' => 'Data Science',
  ),
  1 => 
  array (
    'id' => 3,
    'title' => 'Business Analysis',
    'slug' => 'business-analysis',
    'summary' => 'The Business Analytics Training Program combines business fundamentals, statistics, data
tools, and analytics techniques to prepare you for roles such as Business Analyst, Data
Analyst, and Strategy Consultant.
You’ll learn how to bridge the gap between data and business decisions with Excel, SQL,
Python, Power BI, Looker, and real-world case studies.',
    'details' => NULL,
    'thumbnail' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776944452/lms/course-thumbnails/courses/offline/business-analysis-thumbnail-qrg6z7jg.jpg',
    'campus' => NULL,
    'schedule_label' => NULL,
    'duration_label' => '6 Months',
    'validity_label' => '1 Year',
    'delivery_mode' => 'Online & Offline',
    'placement_label' => '100% Job Placement Guarantee Assurance',
    'audience' => NULL,
    'batch_size' => NULL,
    'language' => NULL,
    'level' => 'Beginner To Advanced',
    'highlights' => '[]',
    'curriculum_modules' => '[{"title":"Business Foundations for Analysts","duration":"3 Weeks","topics":[{"title":"","details":"\\u25cf Business Models & Metrics: Revenue, margin, CAC, LTV, churn, ARPU, cohort\\r\\nconcepts across B2B\\/B2C, SaaS, E-com, Retail, BFSI.\\r\\n\\u25cf Problem Framing: Convert open-ended asks into measurable hypotheses and KPIs.\\r\\nOutcome: Speak the language of business; pick the right metric for the right question."}],"project":""},{"title":"Excel & Google Sheets for BA","duration":"1 Month","topics":[{"title":"","details":"\\u25cf Scenario Modelling: Goal Seek, Solver for pricing, discounts, inventory; sensitivity &\\r\\nwhat-if tables.\\r\\n\\u25cf Executive Dashboards: Multi-page KPI packs for CXOs; dynamic narratives using charts\\r\\n& callouts.\\r\\n\\u25cf Collaboration: Sheets with protected ranges, comments, approvals for cross-functional\\r\\nworkflows."}],"project":"Pricing & Profitability Simulator for a product line."},{"title":"SQL\\/MySQL & Data Modelling","duration":"1.5 Month","topics":[{"title":"","details":"Analytical SQL: Joins for funnels, window functions for cohorts\\/retention, CTEs for\\r\\nreadability, HAVING for post-aggregation filters.\\r\\n\\u25cf Dimensional Modelling: Star schemas (facts\\/dimensions) to power BI dashboards.\\r\\n\\u25cf Performance: Indexes, partitioning, query plans to keep dashboards snappy.\\r\\nTools (with purpose): MySQL Workbench, dbt-style transformations inside SQL, BI\\r\\nconnections to Power BI\\/Looker"}],"project":"End-to-end Sales & Retention mart (SQL models \\u2192 BI dashboards)"},{"title":"Statistics for Business Decisions","duration":"1 Month","topics":[{"title":"","details":"Descriptive & Inferential Stats: Confidence intervals, hypothesis testing\\r\\n(t\\/chi-square\\/ANOVA), effect size.\\r\\n\\u25cf A\\/B Testing & Experiment Design: Power analysis, lift, guardrails; read experiment\\r\\nresults responsibly.\\r\\n\\u25cf Forecasting: Moving averages, exponential smoothing; intro to ARIMA for demand\\r\\nplanning."}],"project":"Marketing campaign A\\/B test analysis + demand forecast for next quarter"},{"title":"Python for Business Analytics","duration":"1 Month","topics":[{"title":"","details":"pandas for Business Tables: Pipelines from raw DB extracts to clean analyst tables.\\r\\n\\u25cf Feature Building: RFM, CLV approximations, seasonality flags; quick scikit-learn\\r\\nmodels for uplift\\/propensity.\\r\\n\\u25cf Story-First Visuals: Matplotlib\\/Seaborn with annotations that answer the \\u201cso what?\\u201d"}],"project":"Churn early-warning score + retention playbook (segment-wise actions)."},{"title":"Power BI & Data Storytelling","duration":"1 Month","topics":[{"title":"","details":"Power BI (Desktop\\/Service\\/Mobile): DAX KPIs, row-level security for teams\\/regions,\\r\\nscheduled refresh, mobile layouts for field ops.\\r\\n\\u25cf Looker Studio: Light, shareable, stakeholder-friendly boards with live connectors.\\r\\n\\u25cf Narrative Structure: Executive summaries, insights > observations, call-to-action slides."}],"project":"Board-ready Business Health Dashboard with insights page & recommended actions."},{"title":"Project Management & Stakeholder Skills","duration":"3 Weeks","topics":[{"title":"","details":"Agile for Analytics: Sprint goals, acceptance criteria, delivery demos.\\r\\n\\u25cf Tools: Jira\\/Trello\\/Asana; issue templates; requirements \\u2192 sign-off loop.\\r\\n\\u25cf Communication: Writing concise insight memos; running stakeholder reviews."}],"project":"Full BA delivery, requirements doc \\u2192 analysis \\u2192 dashboard \\u2192 exec memo."}]',
    'additional_benefits' => '["\\u2714 100% Job Placement Guarantee","\\u2714 Case Studies + Real Industry Projects","\\u2714 ATS-Friendly Resume Building & LinkedIn Optimisation","\\u2714 Mock Interviews + Business Case Interviews","\\u2714 Freelancing Support + GitHub Portfolio Building","\\u2714 Personality Development Training (Alternate Saturdays)"]',
    'learner_note' => 'After completing this program, a fresher will have the knowledge of a 1-year + experienced
professional, while working professionals can confidently switch or upskill into high-demand
roles',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-21 08:53:17',
    'updated_at' => '2026-04-23 11:40:45',
    'category_name' => 'Data Science',
  ),
  2 => 
  array (
    'id' => 4,
    'title' => 'Data Analytics',
    'slug' => 'data-analytics',
    'summary' => 'The Data Analysis Training Program is designed for learners who want to become job-ready
Data Analysts in just 6 months. With a step-by-step progression from basics to advanced
topics, you’ll gain expertise in Excel, SQL, Python, MongoDB, Power BI, and Looker along
with real-world projects.
This program is perfect for freshers, working professionals, and freelancers aiming for
data-driven careers.',
    'details' => NULL,
    'thumbnail' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776944308/lms/course-thumbnails/courses/offline/data-analytics-thumbnail-ivwr6ab4.jpg',
    'campus' => NULL,
    'schedule_label' => NULL,
    'duration_label' => '6 Months',
    'validity_label' => '1 Year',
    'delivery_mode' => 'Online & Offline',
    'placement_label' => '100% Job Placement Guarantee Assurance',
    'audience' => NULL,
    'batch_size' => NULL,
    'language' => NULL,
    'level' => 'Beginner To Advanced',
    'highlights' => '[]',
    'curriculum_modules' => '[{"title":"Excel & Google Sheets","duration":"1 Month","topics":[{"title":"","details":"\\u25cf Formulas & Functions: IF\\/IFS, VLOOKUP\\/XLOOKUP, HLOOKUP, INDEX-MATCH,\\r\\nTEXT\\/DATE functions for automated reporting.\\r\\n\\u25cf Data Cleaning: Remove duplicates, split\\/merge columns, handle blanks, standardise\\r\\ntext\\u2014so datasets are \\u201canalysis-ready.\\u201d\\r\\n\\u25cf Pivot Tables & Charts: Summarise large tables into KPIs; build slicer-driven dashboards\\r\\nfor management reviews.\\r\\n\\u25cf Automation with VBA: Write macros to refresh reports, reshape files, and email\\r\\nsummaries\\u2014cut manual work to minutes.\\r\\n\\u25cf Google Sheets for Collaboration: Real-time sharing, version history, app-scripts\\/add-ons\\r\\nfor lightweight automation"}],"project":"Executive Sales Dashboard (auto-refresh + PDF export + KPI alerts)."},{"title":"SQL, MySQL & NoSQL (MongoDB)","duration":"1.5 Month","topics":[{"title":"Relational SQL (MySQL)","details":"\\u25cb Core Querying: SELECT\\/FROM\\/WHERE, ORDER BY\\/LIMIT, GROUP BY\\r\\nwith COUNT\\/SUM\\/AVG\\/MIN\\/MAX.\\r\\n\\u25cb Joins: INNER\\/LEFT\\/RIGHT\\/FULL to stitch customer, order, product, and\\r\\ntransaction tables.\\r\\n\\u25cb Logic & Subqueries: CASE expressions; subqueries\\/derived tables for complex\\r\\nfilters.\\r\\n\\u25cb Window Functions: ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD to\\r\\nbuild cohort analyses and trends.\\r\\n\\u25cb CTEs & Performance: CTEs for readable analytics; indexes & EXPLAIN plans\\r\\nfor faster queries.\\r\\n\\u25cb DML & Governance: INSERT\\/UPDATE\\/DELETE\\/MERGE; transactions\\r\\n(BEGIN\\/COMMIT\\/ROLLBACK) for data integrity."},{"title":"NoSQL (MongoDB)","details":"\\u25cb JSON Documents & CRUD: Flexible schemas for clickstreams\\/catalogues.\\r\\n\\u25cb Aggregation Pipeline: Grouping, lookups, projections for semi-structured\\r\\nanalytics at scale.\\r\\n\\u25cb Indexes: Speed up reads on high-traffic collections.\\r\\nTools (with purpose): MySQL Workbench\\/SSMS for query IDEs;\\r\\n\\r\\npandas-sqlalchemy to pull data into Python; Power BI\\/Looker to visualise SQL\\r\\noutputs."}],"project":"Customer Segmentation using SQL joins + window functions; product funnel in MongoDB Aggregation Pipeline."},{"title":"Python for Data Analysis","duration":"2 Months","topics":[{"title":"","details":"\\u25cf Core Python \\u2192 OOP: Data types, loops, functions, error handling, OOP for reusable\\r\\nanalytics utilities; file I\\/O (CSV\\/JSON\\/Excel).\\r\\n\\u25cf NumPy: Vectorised calculations, broadcasting, matrix ops for fast number-crunching.\\r\\n\\u25cf Pandas: Data wrangling, joins\\/merge, groupby, missing-value treatment, feature creation;\\r\\ntime-series resampling.\\r\\n\\u25cf Visualisation: Matplotlib\\/Seaborn for trends, distributions, correlations; export to\\r\\nimages\\/PDF for stakeholders.\\r\\n\\u25cf Intro ML (scikit-learn): Train\\/test split, scaling\\/encoding, linear\\/logistic regression,\\r\\nk-means for first predictive insights.\\r\\n\\u25cf Automation: Batch jobs to clean files, refresh KPIs, and email dashboards."}],"project":"E-commerce EDA + churn-risk early-warning report (Python notebooks \\u2192 HTML executive brief)."},{"title":"Business Intelligence & Data Visualisation","duration":"1 Month","topics":[{"title":"","details":"\\u25cf Power BI Desktop \\u2192 Service \\u2192 Mobile: Data modelling, relationships, DAX measures,\\r\\ndrilldowns, Row-Level Security, scheduled refresh, mobile views.\\r\\n\\u25cf Looker Studio: Live connectors (Sheets\\/BigQuery\\/MySQL), interactive scorecards,\\r\\nshareable links for stakeholders."}],"project":"Company-wide KPI Command Center (Sales, Inventory, Marketing, Finance) with scheduled refresh & RLS."},{"title":"Project Management for Analysts","duration":"2 Weeks","topics":[{"title":"","details":"\\u25cf Frameworks: Agile\\/Scrum\\/Kanban basics for sprint-based analytics.\\r\\n\\u25cf Tools: Jira\\/Trello\\/Asana for backlog, sprints, task boards; attach reports & context for\\r\\ntraceability."}],"project":"Sprint-planned analytics backlog with stakeholder sign-offs & release notes."}]',
    'additional_benefits' => '["\\u2714 100% Job Placement Guarantee","\\u2714 Mock Interviews & Resume Building (ATS-Friendly)","\\u2714 LinkedIn Profile Optimisation for Job Search","\\u2714 Personality Development Classes (Alternate Saturdays)","\\u2714 Hands-on Projects + Capstone Project","\\u2714 Freelancing Training (Upwork","Fiverr","Freelancer)"]',
    'learner_note' => 'After completing this program, a fresher will have the knowledge of a 1-year + experienced professional, while working professionals can confidently switch or upskill into high-demand roles.',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-21 10:54:25',
    'updated_at' => '2026-04-23 11:38:21',
    'category_name' => 'Data Science',
  ),
  3 => 
  array (
    'id' => 5,
    'title' => 'Cyber Security',
    'slug' => 'cyber-security',
    'summary' => 'Embark on your cybersecurity journey with the CodeIn Yourself Ethical Hacker course.
Designed for both beginners and professionals, it offers hands-on training in Anonymity,
Cryptography, System Hacking, Deception Technology, and IoT Security.
You’ll explore the Dark Web, secure cloud systems, and apply AI-driven threat intelligence
through real-world simulations and expert guidance.
This course equips you with the skills to protect digital environments, tackle advanced cyber
challenges, and stay ahead in the ever-evolving cybersecurity field.',
    'details' => NULL,
    'thumbnail' => 'https://res.cloudinary.com/dqxg5hhfi/image/upload/v1776944276/lms/course-thumbnails/courses/offline/cyber-security-thumbnail-f6pryula.jpg',
    'campus' => NULL,
    'schedule_label' => NULL,
    'duration_label' => '6 Months',
    'validity_label' => '1 Year',
    'delivery_mode' => 'Online & Offline',
    'placement_label' => '100% Job Placement Guarantee Assurance',
    'audience' => NULL,
    'batch_size' => NULL,
    'language' => NULL,
    'level' => 'Beginner To Advanced',
    'highlights' => '[]',
    'curriculum_modules' => '[{"title":"Foundations of Cybersecurity & Ethical Hacking","duration":"1 Month","topics":[{"title":"","details":"Master the art of ethical hacking with safe testing, strong cryptography, and global cyber laws to defend the digital world\\r\\n Introduction to Ethical Hacking\\r\\n\\r\\n The Ethical Hacker Methodology\\r\\n Virtualization for Safe Testing\\r\\n Cryptography Basics & Advanced Algorithms\\r\\n Cyber Law & International Standards"}],"project":""},{"title":"Reconnaissance & Information Gathering","duration":"1 Month","topics":[{"title":"","details":"Uncover, scan, and secure\\u2014learning the essentials of reconnaissance, enumeration, and password defense in ethical hacking\\r\\n\\r\\n Foot printing & Reconnaissance\\r\\n Google & Shodan Dorks\\r\\n Scanning Networks\\r\\nEnumeration\\r\\nPassword Security"}],"project":""},{"title":"Exploitation & Attacks","duration":"1 Month","topics":[{"title":"","details":"From exploits to DoS, master how attackers break in and learn the defenses that keep systems safe\\r\\n\\r\\n\\r\\n Exploit Kits\\r\\n System Hacking (Access, Privilege Escalation, Control)\\r\\n Malware Threats\\r\\n Sniffing Network Traffic\\r\\n Denial of Service (DoS) Attacks"}],"project":""},{"title":"Network, Mobile & IoT Security","duration":"1 Month","topics":[{"title":"","details":"Secure the future by mastering wireless, mobile, IoT, and web hacking with OWASP\\u2019s top defenses\\r\\n\\r\\n\\r\\n Hacking Wireless Networks (WEP, WPA, WPA2)\\r\\n Hacking Mobile Platforms\\r\\n IoT & OT Hacking\\r\\n Website Security (SQLi, XSS, etc.)\\r\\n OWASP Top 10 Web Risks"}],"project":""},{"title":"Human & Advanced Cyber Defense","duration":"1 Month","topics":[{"title":"","details":"Explore the human, technical, and hidden sides of cybersecurity\\u2014from social engineering to darknet defense\\r\\n\\r\\n\\r\\n\\u25cf Social Engineering Attacks & Defenses\\r\\n\\u25cf Red Team vs. Blue Team Exercises\\r\\n\\u25cf Vulnerability Analysis\\r\\n\\u25cf Deception Technology (Honeypots & Traps)\\r\\n\\u25cf Darknet \\/ Dark Web & Deep Web Exploration"}],"project":""},{"title":"Future Tech & Career Readiness","duration":"1 Month","topics":[{"title":"","details":"Secure the cloud, harness AI, analyze threats, solve cybercrimes, and unlock a career in ethical hacking\\r\\n\\r\\n\\r\\n Cloud Computing Security\\r\\n AI & ML Role in Cybersecurity\\r\\n SOC & Threat Intelligence\\r\\n Cyber Crime Case Investigation\\r\\n Job Opportunities & Career in Ethical Hacking"}],"project":""}]',
    'additional_benefits' => '["\\u2714 100% Job Placement Assistance","\\u2714 Real-Time Cyber Attack Simulations & Labs","\\u2714 Global Certifications Prep (CEH","CompTIA","CISSP)","\\u2714 LinkedIn & Resume Boost for Cybersecurity Roles","\\u2714 Personality Development & Communication Skills","\\u2714 Hands-on Projects + Final Capstone in Security","\\u2714 Freelancing Training for Bug Bounty & Pentesting"]',
    'learner_note' => 'After completing this program, a fresher will have the knowledge of a 1-year + experienced professional, while working professionals can confidently switch or upskill into high-demand roles.',
    'is_active' => 1,
    'sort_order' => 0,
    'created_at' => '2026-04-21 11:05:49',
    'updated_at' => '2026-04-23 11:37:49',
    'category_name' => 'Cyber Security',
  ),
);
        $categoryMap = Schema::hasTable('categories')
            ? DB::table('categories')->pluck('id', 'name')->all()
            : [];

        foreach ($rows as $row) {
            $categoryName = $row['category_name'] ?? null;

            if ($categoryName === null || isset($categoryMap[$categoryName])) {
                continue;
            }

            DB::table('categories')->updateOrInsert(
                ['name' => $categoryName],
                [
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }

        $categoryMap = Schema::hasTable('categories')
            ? DB::table('categories')->pluck('id', 'name')->all()
            : [];

        foreach ($rows as $row) {
            $row['category_id'] = $row['category_name'] !== null
                ? ($categoryMap[$row['category_name']] ?? null)
                : null;

            unset($row['category_name']);

            DB::table('offline_courses')->updateOrInsert(
                ['id' => $row['id']],
                $row
            );
        }
    }

    private function seedWorkshops(): void
    {
        if (! Schema::hasTable('workshops')) {
            return;
        }

        $rows = array (
);

        foreach ($rows as $row) {
            DB::table('workshops')->updateOrInsert(
                ['id' => $row['id']],
                $row
            );
        }
    }
}
